### ISSUE TITLE
Panel Q&A: Especial Líderes Técnicos

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#108]
Panelistas:

Nombre :
Posición Laboral / Descripción:
Compañia:
Biografía Corta :

Foto perfil: (preferible 400x400, ejemplo: la imagen del perfil de twitter)

Social Media:
Twitter / Github / linkedin / Blog / Web Site

La información anterior puede ser en inglés o español.

**Comment by fcontreras** [comment]
**Nombre:** Francisco Contreras
**Posición Laboral:** CTO 
**Compañía:** GInIEm S.A. (Managua, Nicaragua)

**Bio**
Ingeniero de sistemas con maestría en informática empresarial, Gerente de Tecnología y desarrollador de software con más de 10 años de experiencia. Miembro del Java User Group Nicaragua, Co-organizador del GDG Managua y Flutter Latinoamerica, entusiasta de Java, tecnologías móviles y conferencista internacional. Trabaja con empresas de todo el mundo en el desarrollo de soluciones comerciales y de marketing que incluyen, entre otras, desarrollo back-end, desarrollo web / escritorio front-end, inteligencia empresarial y desarrollo móvil. Disfruta de los desafíos y proyectos que exigen hacer un esfuerzo adicional para lograr resultados extraordinarios.

**Foto**
![frank-color-512](https://user-images.githubusercontent.com/528810/180064943-18ff14ea-f5f6-49c5-a7f4-15008a3545bf.png)

**Social Media**
- Twitter: @Frank_JCG
- LinkedIn: /in/fjcontrerasg/

**Comment by chrisom79** [comment]
Nombre : Christian Omar Gomez
Posición Laboral / Descripción: Principal Cloud Developer
Compañia: Oracle
Biografía Corta : Ingeniero en Sistemas Computacionales con 15 años trabajando en la industria de las telecomunicaciones y 2 años haber trabajado en un instituto de investigacion (CIMAT). Actualmente parte de varios proyectos en la Oracle Cloud Infrastructure. Y tambien parte de la GDL JUG por mas de 5 años.

Foto perfil: (preferible 400x400, ejemplo: la imagen del perfil de twitter)
![yo_big](https://user-images.githubusercontent.com/8468544/180065535-3389a8fd-54a2-445f-88b6-3c7b27da5369.jpeg)

Social Media:
Twitter: https://twitter.com/chrisom
Github: https://github.com/chrisom79
 linkedin: https://www.linkedin.com/in/chrisom-java

**Comment by ecabrerar** [comment]
@BrayanMnz favor agregar estas informaciones al sitio de jconf dominicana
