### ISSUE TITLE
 Lanzar sitio de JConf Dominicana 2023

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#116]
Tareas a realizar:
* Actualizar fecha del evento
* Descripción del evento y modalidad del evento
* Agregar el comité del evento: está relacionado con el #74

**Comment by vacax** [comment]
¿Donde ponemos la información del comité @ecabrerar ?.

**Comment by BrayanMnz** [comment]
Fecha tentativa release del site : 

28 Febrero 2023.
