### ISSUE TITLE
Evaluar plantilla para el sitio web de JConf Dominicana 2023

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#117]
Se desea actualizar la parte visual de sitio web de JConf Dominicana para la edición 2023, para tales fines evualar algunas plantillas html que sean de fácil adaptación a thymeleaf, el motor de plantilla que usamos.

**Comment by BrayanMnz** [comment]
Plantillas a evaluar : 

- https://preview.themeforest.net/item/meeta-event-conference/full_screen_preview/35814862?_ga=2.226449114.1334457916.1675308853-813877005.1637645268

- http://preview.themeforest.net/item/event-organizer-for-conference-and-event/full_screen_preview/19947982?_ga=2.193265133.1334457916.1675308853-813877005.1637645268 

- http://preview.themeforest.net/item/eventor-conference-event-html-template/full_screen_preview/20599431?_ga=2.193265133.1334457916.1675308853-813877005.1637645268

**Comment by BrayanMnz** [comment]
Por favor comentar con el número de su plantilla preferida. 
@ecabrerar, @zerh, @vacax, @SiriusDarkz @xTryHard

**Comment by ecabrerar** [comment]
A mi me gusta la 1 y la 3. @BrayanMnz como es el tema del licenciamiento para estas plantillas?. 
Nosotros tenemos el repositorio público y alguien puede clonar el repositorio y utilizar el html, no tendríamos inconvenientes con los creadores de la plantilla?

**Comment by vacax** [comment]
Estoy con @ecabrerar me gustan la opción 1 y la 3. Sobre el licenciamiento, nosotros con la compra entiendo que tenemos la licencia, si alguien lo clona y no lo paga, entonces ese que copio tendría el problema.

**Comment by zerh** [comment]
A mi me parece el 3ro

**Comment by zerh** [comment]
Por lo conversmos en la reunion, vote entonces por la primera

**Comment by BrayanMnz** [comment]
Decidido en reunión 7 Febrero, 2023. 

Plantilla seleccionada : 

https://preview.themeforest.net/item/meeta-event-conference/full_screen_preview/35814862?_ga=2.226449114.1334457916.1675308853-813877005.1637645268

**Comment by ecabrerar** [comment]
@BrayanMnz cerrar este issue y proceder a adquirir la plantilla seleccionada.

**Comment by BrayanMnz** [comment]
Plantilla adquirida, se encuentra dentros de los activos de la comunidad en una carpeta destinada para estos fines. 
Factura de la adquisición también. 
cualquier duda comunicarse conmigo y/o Eudris Cabrera.
