### ISSUE TITLE
Crear mensaje de Lanzamiento JConf Dominicana 2023

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#122]
Tomar como referencia el archivo https://docs.google.com/document/d/1_gZnE7mvOKhS0hlKFJ1gw89FVqEUcjBfhCoaB_l7UH8/edit?usp=sharing

Otro:
https://telegra.ph/Conference-Kickoff---Lanzamiento-JConf-Dominicana-2022-05-27

**Comment by ecabrerar** [comment]
@BrayanMnz @vacax darle un vistazo por favor
https://docs.google.com/document/d/1F7i4YFZs1POP7ym8pvQU5W4pVvSBl8L76yVikliO_Mg/edit?usp=sharing

**Comment by BrayanMnz** [comment]
Esta parte 

Esta es tú oportunidad de participar en este fantástico evento organizado ... hasta por favor contáctanos a team@jconfdominicana.org


Me gusta más como primera parte del documento, ya que el resumen de lo que es JConf estará en otros documentos incluyendo este pero al final del mismo. 

Después todo me parece bien, solo ese pequeño cambio en la estructura.

**Comment by ecabrerar** [comment]
https://telegra.ph/Conference-Kickoff---Lanzamiento-JConf-Dominicana-2023-04-03

**Comment by BrayanMnz** [comment]
LGTM!

**Comment by vacax** [comment]
Veo bien el documento, también podemos ocupar el comentario realizado por @BrayanMnz.

**Comment by ecabrerar** [comment]
La información fue publicada en el grupo de telegram
