### ISSUE TITLE
Crear documento para patrocinadores

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#123]
Crear prospecto de patrocinio:
Español : https://docs.google.com/presentation/d/1UYy85iiBOXbQWraM77ZMoz5qldKFhlIiC4DQsrf74V4/edit?usp=sharing

English:
https://docs.google.com/presentation/d/1F7m1KxOzzmyUCIecIb9KIoTOQYcRGVEE0WgI91Bawj0/edit?usp=sharing

**Comment by BrayanMnz** [comment]
https://docs.google.com/presentation/d/1TGg-60WRKRRop8tgJj-o_-Lq8GSfVrScULEpryp9M5k/edit?usp=sharing

https://docs.google.com/presentation/d/1QgAlkINx_bKiqBTn4fQvWw4Xir_xThTC7RQtdMTFYDs/edit?usp=sharing

**Comment by BrayanMnz** [comment]
https://docs.google.com/presentation/d/1QgAlkINx_bKiqBTn4fQvWw4Xir_xThTC7RQtdMTFYDs/edit#slide=id.g59dd8fa50c_0_6

**Comment by fredpena** [comment]
@BrayanMnz 

Algunas notas a considerar


**Español:**
- La fecha no esta en el documento
- Tiene dos paginas de paquetes de patrocinio.
- En página 11 dice que se el valor expresado es en Pesos, pero el paquete esta en dolares.


**Discrepancia  en versiones (Ingles y  Español):**

- Tecnologías (Página 3)
- Pobación (Página 7)
- La gafricas no estan de acordes (Página 8)
- Cómo ser patrocinador (Página 10)


**Observaciones:**

- No se bueno poner donde se va a celebrar?

**Comment by ecabrerar** [comment]
@BrayanMnz hiciste las modificaciones al documento?

**Comment by BrayanMnz** [comment]
Si, favor verificar el caso de Cómo ser patrocinador @ecabrerar en la página 10.

**Comment by ecabrerar** [comment]
@BrayanMnz yo entiendo que después de la página 9 que dice Paquetes de Patrocinios, debe ir la página que están los paquetes como tal.
