### ISSUE TITLE
Revisar el mensaje que estaremos enviando a los speakers

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#134]
@xTryHard favor darle un vistazo a este documento para proceder a enviar el mensaje a las personas que conocimos en devnexus

https://docs.google.com/document/d/1pxDVcvujcdRgN0sOEzEaNDsxWWDXrFohvEOZSAXYiQs/edit?usp=sharing

**Comment by xTryHard** [comment]
Me parece muy bien. Anexo el mensaje actualizado con algunas sugerencias:

Hi!
It was really nice meeting you at DevNexus. Those days were filled with rich information and lengthy discussions on the Java ecosystem and the Java community.

Following our conversation regarding the Dominican Republic Java User Group, we will lead JConf Dominicana 2023 on July 21st and 22nd.

JConf Dominicana is a Java technologies conference organized by the Dominican Republic JUG. It is designed to discuss the latest about the Java ecosystem, including alternatives JVM languages, Web\Mobile development, and most trending Cloud technologies. This year is our first in-person installment following two virtual releases.

The conference offers a unique networking opportunity for developers, companies, and startups, along with a chance to enjoy the pristine beaches, cloud-forest treks, and the welcoming villages that the island has to offer.

If you would like to become one of our speakers, our Call for Paper is open now.

We are looking for quality content from both local and international speakers to inspire our communities. We work for an inclusive event, with sessions comprising different levels: beginner, intermediate, advanced.
