### ISSUE TITLE
Publicar encuesta en redes sociales

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#136]
Para mantener las redes activas, sería bueno publicar la siguiente encuesta:

Para JConf Dominicana 2023, tendremos talleres prácticos de la mano de experimentados profesionales del mundo Java, 
¿Cuál tema te gustaría más?

1. Spring Boot 3
2. Introducción a Apache Kafka
3. Asegurando tu ciclo de desarrollo (DevSecOps)
4. Desarrollo de aplicaciones con Quarkus  
5. Jakarta EE 10 y Microprofile 6
6. Novedades de Java 17 a Java 20

@BrayanMnz favor publicar en las siguientes redes:
Twitter
Linkedin
Instagram

**Comment by fredpena** [comment]
_3. Asurando tu ciclo de desarrollo (DevSecOps)_

Asumo que sera Asegurando.

**Comment by BrayanMnz** [comment]
Twitter solo admite 4 opciones para encuestas.

**Comment by ecabrerar** [comment]
> Twitter solo admite 4 opciones para encuestas. Instagram también solo admite 4 opciones.

En esas dos publicar de la siguiente forma:


    Spring Boot 3
    Asegurando tu ciclo de desarrollo (DevSecOps)
    Jakarta EE 10 y Microprofile 6
    Novedades de Java 17 a Java 20

**Comment by BrayanMnz** [comment]
Listo
