### ISSUE TITLE
Banner para publicidad de la conferencia

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#138]
Hola @fredpena ,

Nosotros necesitamos un banner principal para el evento, que lo usaremos parecido a esta publicación:
https://twitter.com/jconfdominicana/status/1550809339497152515
Inicialmente no lleva los patrocinadores.
Otros ejemplos:
https://twitter.com/jconfdominicana/status/1549778716624142336
https://twitter.com/jconfdominicana/status/1547744247247302662
https://twitter.com/jconfdominicana/status/1548044201543184384

Luego del banner principal necesitamos otro banner para la publicación de los patrocinadores
https://twitter.com/jconfdominicana/status/1550871998859022337
https://twitter.com/jconfdominicana/status/1551696691786665986
https://twitter.com/jconfdominicana/status/1551698253351100416

Y un tercero para la publicidad de las charlas:
https://twitter.com/jconfdominicana/status/1550633682200838155
https://www.instagram.com/p/CgSUZnWMSv0/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==

Tanto el de los patrocinadores como el de las charlas debe ser editable, porque pensamos reutilizarlo.

**Comment by ecabrerar** [comment]
@fredpena viste los ejemplos que te pasé?

**Comment by fredpena** [comment]
Saludo @ecabrerar;

Hable con mi contacto, ya esta trabajando en eso, este finde de semana estara enviandome algunas muestras.

**Comment by fredpena** [comment]
![WhatsApp Image 2023-05-15 at 11 51 04 (1)](https://github.com/JavaDominicano/conference/assets/5680906/339e7330-0d2c-4723-8ce7-a65acad58e76)
![WhatsApp Image 2023-05-15 at 11 51 04](https://github.com/JavaDominicano/conference/assets/5680906/00edb61c-b2cb-4ee5-af48-d509ef0baabc)

**Comment by fredpena** [comment]
Ahi hay dos modelos para los post de los speakers
