### ISSUE TITLE
Invitar a estudiantes, colegas y amigos a enviar propuestas para JConf Dominicana 2023

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#139]
Tenemos la necesidad de subir la participación de propuestas de charlistas locales para JConf Dominicana 2023.

Invitar a  estudiantes, colegas y amigos a enviar propuestas para JConf Dominicana 2023
https://www.papercall.io/jconf-dominicana-2023

**Comment by ecabrerar** [comment]
@vacax @SiriusDarkz @fredpena @BrayanMnz vamos a motivar a los conocidos para que envíen propuestas

**Comment by ecabrerar** [comment]
Alguna novedad con este tema @vacax ? Se está moviendo por lo menos? No he visto nuevas propuestas..

**Comment by BrayanMnz** [comment]
@ecabrerar esto debería ser cerrado ya, el call for paper terminó.
