### ISSUE TITLE
Seleccionar iconos que representen la palabra Live Coding y Workshops

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#145]
![image](https://github.com/JavaDominicano/conference/assets/2789130/8f0e73c9-c679-4c67-8352-ad28f6c91248)
Reemplazar iconos de Live Coding y Workshops por los iconos correspondientes a cada uno

**Comment by BrayanMnz** [comment]
En este commit se agregan íconos que representan a Live Coding y Workshop (según mi criterio, puede ser cambiado por otro si alguien no está de acuerdo)
https://github.com/JavaDominicano/conference/pull/147/commits/ac463bb90fc2ab71837055a28fd5722e65967a9f
