### ISSUE TITLE
Incluir información de AN Uniformes

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#156]
@fredpena favor solicitar el logo y las redes sociales de AN Uniformes para ser colocado en el sitio como patrocinador.

**Comment by fredpena** [comment]
![Logo AN_Mesa de trabajo 1](https://github.com/JavaDominicano/conference/assets/5680906/916d4293-7d5f-4397-ba18-cc5e30b869d7)
![Logo AN_Mesa de trabajo 1](https://github.com/JavaDominicano/conference/assets/5680906/63d26d7d-e369-4b79-aabb-99d82c7254b5)

**Comment by ecabrerar** [comment]
agregado al sitio como sponsor
