### ISSUE TITLE
Logo del comité de ISC

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#159]
Buenas @darvybm , favor incluir el logo y las informaciones de redes sociales del comité de isc.

**Comment by darvybm** [comment]
Instagram: https://www.instagram.com/ciccpucmm/ (@ciccpucmm)
Twitter: https://twitter.com/ciccpucmm (@ciccpucmm)
Logo:
![Image](https://github.com/JavaDominicano/conference/assets/69068214/1478cec1-8f85-430c-b152-f663e7c1cc88)

**Comment by ecabrerar** [comment]
Incluido con el site
