### ISSUE TITLE
Traducir charlas

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#161]
1.
**title:**Bienvenidos al fin de la era del siempre lo hicimos así" Lecciones implementando Software
**abstract:**La mayoría de nosotros ha escuchado las 7 palabras más caras en  los negocios: \"Siempre lo hicimos así\" y podemos ver la resistencia al cambio, y puedes estar seguro de que la solución que ofreces es necesario, pero cómo ser un agente de cambio utilizando la tecnología, ¿es posible lograrlo?
**description:**Bienvenidos al fin de la era del siempre lo hicimos así.Lecciones implementando software..*Hoy quiero hablarte sobre la gestión del cambio en  implementaciones de software. En los últimos años, hemos visto una explosión de tecnologías  que han transformado la manera en que trabajamos y colaboramos. Sin embargo, implementar un nuevo software no es solo una cuestión técnica, sino que también implica un cambio cultural y organizacional que puede ser difícil de manejar.En esta charla, te daré las claves para ser un agente de cambio efectivo utilizando la tecnología como puente. Descubrirás por qué la gestión del cambio es crucial en las implementaciones de software, qué habilidades y herramientas necesitas para liderar un cambio exitoso y cómo puedes influir positivamente en el cambio desde cualquier posición.

2.
**title:** Despliegue seguro y escalable de aplicaciones web con Vaadin Flow, Docker y Traefik
**abstract:** Despliega aplicaciones web desarrolladas con Vaadin Flow de manera segura y escalable utilizando las tecnologías Docker y Traefik. Combina estas herramientas para simplifica el proceso de despliegue, garantiza la seguridad y asegura la disponibilidad en entornos de alta demanda.
**description:** Sumérgete en el fascinante mundo del despliegue de aplicaciones web con Vaadin Flow, Docker y Traefik. En esta charla, te guiaremos a través de un viaje emocionante donde descubrirás cómo asegurar y escalar tus aplicaciones web de manera impecable. Aprende a aprovechar al máximo las tecnologías más modernas mientras simplificas el proceso de despliegue. Exploraremos cómo la combinación de Vaadin Flow, Docker y Traefik te permitirá alcanzar niveles superiores de seguridad y garantizar una experiencia fluida incluso en los entornos más exigentes. ¡No te pierdas esta oportunidad de aprender los secretos detrás del éxito del despliegue de aplicaciones web seguras y escalables!

3.
**title:** El auge de los DevRels y su importancia en tu organización
**abstract:** ¿Por qué vemos un auge en los llamados DevRels? ¿Qué son? ¿Qué hacen? En esta charla vamos a conversar con Yuri, Developer Relations Advocate(DevRel) en Supabase y aprender sobre la importancia de esta figura en compañías de SAAAS y todas aquellas que tengan como a su customer persona a developers.
**description:** Desde qué son, los tipos, la forma en que los DevRels ayudan a incrementar ventas y el conocimiento de tu producto en la comunidad son algunos de los temas que cubrirá Yuri en su charla sobre El auge de los DevRels y su importancia en tu organización. Aprenderás sobre la forma en que esta labor se desempeña no sólo de forma externa frente a la comunidad y usuarios pero también cómo se ve en lo interno de la compañía, cómo segmentar tu audiencia para fines de marketing de tu producto y comunidad , la importancia de la creación de contenido para tus metas y muchas cosas más.

**Comment by fredpena** [comment]
**Title:** Secure and Scalable Deployment of Web Applications with Vaadin Flow, Docker, and Traefik.

**Abstract:** Deploy web applications developed with Vaadin Flow securely and scalably using Docker and Traefik technologies. Combine these tools to simplify the deployment process, ensure security, and guarantee availability in high-demand environments.

**Description:** Dive into the fascinating world of web application deployment with Vaadin Flow, Docker, and Traefik. In this talk, we will guide you through an exciting journey where you will discover how to ensure seamless security and scalability for your web applications. Learn how to make the most of the latest technologies while simplifying the deployment process. We will explore how the combination of Vaadin Flow, Docker, and Traefik will enable you to achieve higher levels of security and ensure a smooth experience even in the most demanding environments. Don't miss this opportunity to learn the secrets behind the success of secure and scalable web application deployment!

**Comment by fredpena** [comment]
**Title:** Welcome to the end of the 'We've always done it this way' era - Lessons in Software Implementation

**Abstract:** Most of us have heard the seven most expensive words in business: 'We've always done it this way.' We can see the resistance to change, and you can be certain that the solution you offer is necessary, but how can we become change agents using technology? Is it possible to achieve it?

**Description:** Welcome to the end of the 'We've always done it this way' era. Lessons in software implementation... Today, I want to talk to you about change management in software implementations. In recent years, we have witnessed an explosion of technologies that have transformed the way we work and collaborate. However, implementing new software is not just a technical matter; it also involves cultural and organizational change that can be challenging to handle.

In this talk, I will provide you with the keys to becoming an effective change agent using technology as a bridge. You will discover why change management is crucial in software implementations, what skills and tools you need to lead successful change, and how you can positively influence change from any position.

**Comment by fredpena** [comment]
**Title:** The Rise of DevRels and Their Importance in Your Organization

**Abstract:** Why do we see a rise in the so-called DevRels? What are they? What do they do? In this talk, we will have a conversation with Yuri, a Developer Relations Advocate (DevRel) at Supabase, and learn about the importance of this role in SaaS companies and any organization whose customer persona is developers.

**Description:** What they are, the different types, and how DevRels help increase sales and product awareness in the community—these are some of the topics Yuri will cover in his talk on The Rise of DevRels and Their Importance in Your Organization. You will learn about how this role is performed not only externally facing the community and users but also internally within the company, how to segment your audience for product marketing and community purposes, the importance of content creation for your goals, and much more.
