### ISSUE TITLE
Iconos Redes Sociales

### ISSUE THREAD

**Issue by fredpena** [JavaDominicano/conference#164]
Solo esta apareciendo el icono de Twitter, los demas salen con icono generico, y el de linkedin no aparece.

![image](https://github.com/JavaDominicano/conference/assets/5680906/a788b9d4-573e-4655-acb0-cb35b5afdc39)

**Comment by ecabrerar** [comment]
Ese es un issue conocido, el icono de linkedin está definido en el css pero en ningún lado ellos lo usan y encontré la sorpresa de que no aparece
