### ISSUE TITLE
Media Sponsor 

### ISSUE THREAD

**Issue by fredpena** [JavaDominicano/conference#172]
- **Name:** Perla García Sánchez 
- **Profesión:** Diseñadora Gráfica 
- **Email:** me@perlagarcia.design
- **Portafolio:** perlagarcia.design

![IMG_20230625_153412_454.jpg](https://github.com/JavaDominicano/conference/assets/5680906/c7218340-feef-4cb0-8c56-f035d5c10e40)

@ecabrerar y @BrayanMnz ahí están los datos de la chica de las artes gráficas

**Comment by ecabrerar** [comment]
@fredpena  el link del portafolio está roto

**Comment by fredpena** [comment]
Voy a hablar con ella, pero puede ir avazando con la demas informacion.

**Comment by ecabrerar** [comment]
Le puse el enlace de linkedin
