### ISSUE TITLE
Cotizar bajantes de la comunidad Java Dominicano

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#184]
Buenos días @fredpena ,
Necesitamos cotizar dos bajantes (banner) con los logos de Java Dominicano y los bases tipo araña.

**Comment by fredpena** [comment]
3,000.00 pesos dos arañas y dos bajantes.

**Comment by fredpena** [comment]
Cotizacion y artes listo, solo se debe mandar a imprimir

**Comment by BrayanMnz** [comment]
Buen día, @fredpena esto se mandó a imprimir?

**Comment by fredpena** [comment]
> Buen día, @fredpena esto se mandó a imprimir? 

Buenos días @BrayanMnz 

Si, esta semana lo entrega Dios mediante.

Juntos con las tasas y shopping (esto son patrocinado)

**Comment by fredpena** [comment]
> 

Es asi, pero aun estamos a tiempo, se hace de una vez

**Comment by ecabrerar** [comment]
@fredpena favor preguntar donde mandaste a hacer los otros bajantes en cuanto saldría un bajante de las dimensiones de este?
![Uploading Techonology-en-ITSS.png…]()

**Comment by fredpena** [comment]
Ya se cotizó, en espera de artes para mandar a imprimir

**Comment by ecabrerar** [comment]
@fredpena recuerda pasarnos las facturas

**Comment by fredpena** [comment]
Aun en espera de que me envien la factura.
