### ISSUE TITLE
Video presentación de speaker del evento

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#189]
Hola @fredpena ,
Algunas observaciones sobre el video:
Incluir el lugar del evento
Incluir patrocinadores diamante

Lugar: Auditorio 1, Edificio A-2, 2do nivel, PUCMM,  Av. Abraham Lincoln esq. Av. Bolívar, Santo Domingo.

Patrocinaores
Swisher Dominicana, Inc: https://drive.google.com/file/d/17E79raNiUSLrtv6lZ1YKoBFWtNvfMk6x/view?usp=drive_link
Nearsure
https://drive.google.com/file/d/1p5KZpIf3cavaSxqu9PvXL4lUOnjXh5Ue/view?usp=drive_link
https://drive.google.com/file/d/1P8WpU_dYGtw5ibNZ9Rk7ZfZR4A_9N-M2/view?usp=drive_link

AN Uniformes
https://drive.google.com/file/d/1RkoXSrzWELKBbKDNWywNwyVhjEf9g895/view?usp=drive_link
https://drive.google.com/file/d/1Rl_nTaq_kFah8pcDD2nLHCo-GvnXo1YX/view?usp=drive_link

PUCMM
![pucmm](https://github.com/JavaDominicano/conference/assets/2789130/2b326d4b-f4c1-4977-9b3b-5906c4c16e80)
![Marca PUCMM (Color)](https://github.com/JavaDominicano/conference/assets/2789130/667ed9af-75e5-479d-9997-db51b4caa34e)

Nota:
Donde hay dos imágenes es para que tomen la que se vea mejor

**Comment by fredpena** [comment]
Listo, video sbudo al Drive
