### ISSUE TITLE
Crear otro banner para publicidad

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#195]
Hola @fredpena , favor solicitar a la diseñadora lo siguiente:

Crear una plantilla usando como base https://drive.google.com/file/d/1wimawW2kTQqTEdbEgPE-Av7i3Qm2jm8X/view?usp=drive_link.

Se desea agregar el lugar del evento y el precio.

Lugar: 
Auditorio I, PUCMM, Av. Abraham Lincoln esq. Av. Bolívar, Santo Domingo.

Fecha:
21-22  de Julio de 2023

Inversión:
RD $1200 pesos

Algunos ejemplos de banner anteriores, solo para que tome la idea más claro:

- https://drive.google.com/file/d/1AsQbWeXrUHcdrNVh5bgedLpc52bbcgxq/view?usp=drive_link- 
- https://twitter.com/BarCampRD/status/1591561866861596672?t=PjX_mbFA29-jsS6500mP1A&s=19

**Comment by fredpena** [comment]
Listo, subido al Drive

Version ingles y español

**Comment by ecabrerar** [comment]
Bien
