### ISSUE TITLE
Promoción JConf 2023 destacando inversión

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#197]
https://drive.google.com/file/d/14r6zC94c3Uza3yg08VMT_j-O-_H7G7qc/view?usp=drive_link

¡No te pierdas todo lo que JConf Dominicana 2023 trae para ti!
Además de contenido interesante, tendremos rifas de licencia de jetbrains, gift cards y mucho más.

La boleta incluye:

Desayuno ligero, Almuerzo y Refrigerios
Camiseta.
Materiales promocionales del evento y nuestros patrocinadores.
Acceso a las conferencias magistrales.
Acceso a las secciones técnicas.

#JConfDominicana2023 #Java #JUGEvents #JVM

**Comment by ecabrerar** [comment]
Publicado en Linkedin y Twitter.
@BrayanMnz puedes hacer una publicación en facebook e instagram?

**Comment by BrayanMnz** [comment]
listo
