### ISSUE TITLE
Publicar PUCMM cómo sponsor

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#199]
Gracias a @pucmm por siempre abrir sus puertas para nuestras actividades a través de la Escuela de Computación y Telecomunicaciones.

https://bit.ly/jconfdominicana-2023-sponsors

#JConfDominicana2023 #Java #JUGEvents #JVM 

Incluir imagen https://drive.google.com/file/d/1KKYgSBUzcdgkiB7g2lOimAD-FZXPjsmj/view?usp=drive_link

**Comment by ecabrerar** [comment]
@BrayanMnz si tienes un espacio de tiempo, favor publicar en todas las redes de jconf

**Comment by fredpena** [comment]
!Gracias PUCMM! Por siempre abrir sus puertas para nuestras actividades a través de la Escuela de Computación y Telecomunicaciones.

Solo agregaria la exclamación.

**Comment by ecabrerar** [comment]
La publicación fue agendada para ser publicada a la 9:00 A.M.
