### ISSUE TITLE
Enviar correo de invitación a empresas y/o personas

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#202]
Hola @xTryHard ,
usando el mensaje https://docs.google.com/document/d/1JTbeqe_mZREJ1smwR5V5cAFXIPRTWT7TxnAiEYLRfIs/edit?usp=sharing, queremos enviar mensajes de invitación a empresas y personas.

Tenemos un listado en el documento donde están los posibles patrocinadores.
Los mensajes deben enviarse desde la cuenta info@jconfdominicana.org.

@BrayanMnz  favor asistir con el tema de usar la cuenta de proton mail.

**Comment by ecabrerar** [comment]
Correo enviado a Argentum Inc

**Comment by ecabrerar** [comment]
Correo enviado a Wepsys

**Comment by ecabrerar** [comment]
Correo enviado a OrionTek

**Comment by xTryHard** [comment]
Correo enviado a Advansys

**Comment by xTryHard** [comment]
Correo enviado a Codemera
