### ISSUE TITLE
Gestionar diseño para el sello

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#213]
Hola @fredpena ,

Este es un prototipo del sello que teníamos https://drive.google.com/file/d/1JPBaI1raCUyD-RcvsvS9k_fLOM5jAwqh/view?usp=drive_link,
Pero ahora tenemos que agregarle las informaciones de la institución.

**Dominicana JUG, Inc.**
**Registro Nacional de Incorporación No.23244/2023**
**RNC No. 4-30-37120-3**
**Santiago, R.D.**

**Comment by fredpena** [comment]
Dominicana JUG, Inc.
Registro Nacional de Incorporación No.23244/2023
RNC No. 4-30-37120-3
Santiago, R.D.

Todo eso debe quedar tal cual, o se puede abreviar?
Por lo menos "Registro Nacional de Incorporación No"

**Comment by fredpena** [comment]
Listo!!!

https://drive.google.com/drive/folders/1rNbU52TzftPuN3UjR_jjmSVaIifKgV5t?usp=drive_link

**Comment by BrayanMnz** [comment]
Entiendo que esto se manejó y aprobó vía Telegram, 
podemos cerrar la tarea. @ecabrerar
