### ISSUE TITLE
Modificar banner de AvatharTech

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#216]
Este banner https://drive.google.com/file/d/1H_IYL5_YSgTTGbmHswZ6UNWA0Lo2tLNt/view?usp=drive_link y https://drive.google.com/file/d/1Os3tJBN9OYP_UbFi8nP2OjWJDlrwMeha/view?usp=drive_link deben decir **Supporter** en lugar de **Supporters Sponsor**.

**Comment by fredpena** [comment]
Listo, ya lo subi al drive tambien
