### ISSUE TITLE
Taller Javalin + javalinVue

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#222]
Título:
Modern Web Development with Javalin and JavalinVue

¿Quieres empezar a crear una aplicación fullstack con Java y VueJS? El framework web Javalin te brinda, JavalinVue, un plugin que da soporte para desarrollar frontends con Vue de una manera simplificada en tu mismo proyecto. Junto a Javalin, hacen una combinación interesante que nos ayudarán a empezar a trabajar en nuestro proyecto en cuestión de minutos.

Los temas que estaremos tratando son:

- 

Bio

Mi nombre es Ivanosevic García. Tengo alrededor de 3 años de experiencia en el mundo del desarrollo conjunto al aseguramiento de calidad de software. Actualmente soy desarollador de Java, y me apasiona ver los nuevos avances al nivel de lenguaje y nuevos proyectos basados en Java. Con relación a la tecnología de Javalin, estoy creando proyectos desde su versión 3.9, que fue lanzada en 2021, y desde entonces he seguido el proyecto. Aparte de haber creado varios proyectos en esta tecnología, me siento confiado en que puedo transmitir mis conocimientos de las versión actual, sobre la misma y de JavalinVue.

Perfil de GitHub: https://github.com/Ivanosevic

**Comment by ivanosevic** [comment]
Título:
Modern Web Development with Javalin and JavalinVue

¿Quieres empezar a crear una aplicación fullstack con Java y VueJS? El framework web Javalin te brinda, JavalinVue, un plugin que da soporte para desarrollar frontends con Vue de una manera simplificada en tu mismo proyecto. Junto a Javalin, hacen una combinación interesante que nos ayudarán a empezar a trabajar en nuestro proyecto en cuestión de minutos.

Los temas que estaremos tratando son:

1. Introducción al framework Javalin 
2. Creación de un proyecto con Javalin
3. Creación de un Rest API con Javalin 
4. Asegurar tu Rest API con Javalin
5. Configuración Javalin y Plugins
6. Integración de Javalin y Vue.Js: JavalinVue
7. Creación de un Frontend para nuestro Rest API con JavalinVue
8. Conclusiones

Bio

Mi nombre es Ivanosevic García. Tengo alrededor de 3 años de experiencia en el mundo del desarrollo conjunto al aseguramiento de calidad de software. Actualmente soy desarollador de Java, y me apasiona ver los nuevos avances al nivel de lenguaje y nuevos proyectos basados en Java. Con relación a la tecnología de Javalin, estoy creando proyectos desde su versión 3.9, que fue lanzada en 2021, y desde entonces he seguido el proyecto. Aparte de haber creado varios proyectos en esta tecnología, me siento confiado en que puedo transmitir mis conocimientos de las versión actual, sobre la misma y de JavalinVue.

Perfil de GitHub: https://github.com/Ivanosevic

**Comment by ecabrerar** [comment]
@ivanosevic tienes una foto de mejor calidad?

**Comment by ivanosevic** [comment]
![DN3A0227](https://github.com/JavaDominicano/conference/assets/24396014/06c9052a-81b3-41ab-99b1-35d0e50e5033)
