### ISSUE TITLE
Hacer banner de publicidad para el taller de docker de Carlos Camacho

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#226]
Titulo: Taller de Contenedores y Orquestadores de Software Para Javeros
Fecha:  2:00 P.M / 21 Julio 2023
Por Carlos Camacho

**Comment by fredpena** [comment]
https://www.canva.com/design/DAFoX-AEdOM/VzFf2KI-rp0hdrCzElO1Hw/edit?utm_content=DAFoX-AEdOM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by xTryHard** [comment]
Listo. https://www.canva.com/design/DAFoX-AEdOM/VzFf2KI-rp0hdrCzElO1Hw/edit
