### ISSUE TITLE
Hacer banner de publicidad de taller de Taller Seguridad para aplicaciones y servicios Java con Keycloak

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#227]
Titulo: Taller Seguridad para aplicaciones y servicios Java con Keycloak
Fecha: 2:00 P.M / 21 Julio 2023
Por Eudris Cabrera

**Comment by xTryHard** [comment]
Listo. https://www.canva.com/design/DAFoX-AEdOM/VzFf2KI-rp0hdrCzElO1Hw/edit
