### ISSUE TITLE
Crear banner con todos los speakers

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#234]
Se desea crear un banner que incluya todos los speakers.
De cada speaker mostrar la siguiente información:

Fotografía
Nombre
Posición / Titulo
Bandera del país

Las fotografía de los speakers estan en el site.
![Screenshot 2023-07-12 at 10-19-46 JConfDominicana 2023](https://github.com/JavaDominicano/conference/assets/2789130/6234985f-bc93-45ae-b94a-6d9368484aad)

**Comment by fredpena** [comment]
Cuando puedan me hacen el feedback de dular, para subir la imagen al drive.

![image](https://github.com/JavaDominicano/conference/assets/5680906/80c0c510-c98b-4830-b284-1d3995a2b1f7)

**Comment by fredpena** [comment]
Lsito, esta en el drive con los cambios
