### ISSUE TITLE
Hacer banner de Publicidad de Taller Creating your own Machine Learning models in Java, with Java and for Java.

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#239]
Titulo: Creating your own Machine Learning models in Java, with Java and for Java.
Fecha: 2:00 P.M / 21 Julio 2023
Por Brayan Muñoz

**Comment by ecabrerar** [comment]
@xTryHard nos puede ayudar con esta tarea?

**Comment by fredpena** [comment]
> Titulo: Creating your own Machine Learning models in Java, with Java and for Java. Fecha: 2:00 P.M / 21 Julio 2023 Por Eudris Cabrera

Ese taller no es Brayan que lo va a dar?
