### ISSUE TITLE
Crear banner especificando la fecha y hora de cierre de la venta de boletas

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#257]
Hola @fredpena,
Tanto para el banner de entrada individual como para el de entrada grupal, agregar mensaje 
**Boletas a la venta hasta el 20/07/2023 a la 6:00 P.M.**

 busca la mejor forma de colocar eso, quizás en canva existan plantillas.

**Comment by fredpena** [comment]
Listo, puede buscarlo en el Drive
