### ISSUE TITLE
Crear banner de ganadores

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#268]
Hola @fredpena,
Tomando el diseño horizontal, queremos hacer un diseño para los ganadores en la rifa.

### Licencias de Jetbrains

- Manuel Cepeda
-  Johnny Reynoso
- Yunior Echavaría

### Ganadores de Amazon Gift Cards

- Alison Perez
- Eugenio Berehulka
- Saul Concepción
- Darling De La Cruz
- José Miguel Rodríguez Kelly 
- Yandra Campusano Fermín
- José Dominique
- Jhonathan Cuesto

### Tazas  de JConf Dominicana

- Garibaldy Martínez Morales
- Edwin Sabala
- Edwin Levinson Mejía Marcelino
- Aluis Marte Hernández

### Taller de certificación de Scrum Master
- Nicolas Alonzo

Cada categoría por separado

**Comment by fredpena** [comment]
Falta un ganador de tasas. Lo hago sin el?

**Comment by fredpena** [comment]
Listo @ecabrerar 

Link: https://drive.google.com/file/d/1SpzOAySt0XWZjv9iXdqAVK9sEK5jTQz0/view?usp=drive_link

**Comment by ecabrerar** [comment]
Publicado
