### ISSUE TITLE
Java Events (https://dev.java/community/events/)

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#283]
Date and location: July 19-20, 2024. Santiago de los caballeros, Dominican Republic.

La descripción del evento lo pueden tomar de https://jconfdominicana.org/

**Comment by fredpena** [comment]
`Correo listo, a epera del link del CFP:`

Email: java_devrel_events_grp@oracle.com

Subject: Inclusion Request for JConf Dominicana in Your Events Calendar

Dear Java Community,

I hope this message finds you well. We are reaching out to kindly request the inclusion of our upcoming event, JConf Dominicana, in your esteemed events calendar. Here are the details for your reference:

Event Name: JConf Dominicana
Date: July 19-20, 2024
Location: Santiago de los Caballeros, Dominican Republic
Website: https://jconfdominicana.org/
Call for Papers: https://jconfdominicana.org/cfp-2024

JConf Dominicana, also known as The Caribbean Java Technologies Conference, is a community-driven event organized by the Dominican Republic Java User Group, (AKA JavaDominicano). This conference serves as a platform to delve into the latest developments in the Java ecosystem, covering topics such as alternative JVM languages, web and mobile development, and the newest trends in cloud computing.

Apart from the rich technical content, JConf Dominicana provides a unique networking opportunity for developers, tech companies, and startups. Attendees will also have the chance to explore the picturesque landscapes of the Dominican Republic, including pristine beaches, cloud-forest treks, and welcoming villages.

We believe that the inclusion of JConf Dominicana in your events calendar would provide valuable information to your audience and contribute to the success of our event. Thank you for considering our request.

Should you need any additional information or have questions, please feel free to reach out. We look forward to the possibility of seeing JConf Dominicana featured in your events calendar.

Best regards,

Team - JConf Dominicana
[team@jconfdominicana.org](mailto:team@jconfdominicana.org)
[www.jconfdominicana.org](https://jconfdominicana.org/)
July 19-20, 2024. Santiago de los Caballeros, Dominican Republic
The Caribbean Java Technologies Conference.
