### ISSUE TITLE
Posibles Talleres JConf Dominicana 2024

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#291]
La idea es poder estructurar algunos talleres para que personas de la comunidad en acompañamiento de miembro del staff puedan dar los talleres.

Actualizar documento https://docs.google.com/spreadsheets/d/1hnOoehfIIknsKfPbgptFC-IT8hHCYkORocyo4auzmzQ/edit?usp=sharing

**Comment by fredpena** [comment]
@ecabrerar y @BrayanMnz agregen los talleres que ustedes tienen pensado impactir.
