### ISSUE TITLE
Promoción de Conferencistas

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#299]
- [x] #300
- [x] #301
- [x] #302
- [x] #303
- [x] #304
- [x] #305
- [x] #307
- [x] #306
- [x] #311
- [x] #312
- [x] #317
- [x] #327
- [x] #328
- [x] #330
- [x] #331
- [x] #332

**Comment by fredpena** [comment]
Todo esta conferencia estan lista, favor de revisar en el Canva
