### ISSUE TITLE
Crear banner de promoción para taller de Freddy Peña y Juan Diego

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#306]
@fredpena se necesita una plantilla para cuando sean dos speakers como es el caso de tu taller

Titulo: Unlocking the Power of Multitenancy (Quarkus and Vaadin Flow)
Speaker : Freddy Peña
Co-Speaker: Juan Diego López

**Comment by fredpena** [comment]
Esta creado, favor revisar el canva, y si esta de acuerdo cerrar el caso
