### ISSUE TITLE
Crear banner con los speakers confirmados a la fecha

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#317]
@fredpena necesitamos un banner con todos los speakers para un mensaje que enviaré a las empresas

**Comment by ecabrerar** [comment]
Algunos ejemplos:

![Speakers-Jconf-RD-1](https://github.com/JavaDominicano/conference/assets/2789130/f7d4ff61-8791-4ea1-906c-a6af51d26311)
![Speakers-Jconf-RD-2](https://github.com/JavaDominicano/conference/assets/2789130/4d6712cd-f0ca-423b-bbd6-3ecb09426b46)

**Comment by ecabrerar** [comment]
@fredpena las imágenes están aquí: https://drive.google.com/drive/folders/1LiEH8NkbMHQWDbrAGal83hJ2C9E09ueE?usp=sharing

**Comment by fredpena** [comment]
Listo.

https://www.canva.com/design/DAGDS8u_1NM/CkX_kAPGSL3rM9sXduhVsQ/edit?utm_content=DAGDS8u_1NM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
