### ISSUE TITLE
Crear banner de promoción para charla de Brayan Muñoz

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#330]
Speaker: Brayan Muñoz
Title: Hablando de basura: Garbage Collector, ¿Qué es?  ¿Cómo funciona? ¿Cuál debería utilizar en mi aplicación?
Organization: Dominican Republic JUG

**Comment by ecabrerar** [comment]
![Brayan Muñoz - ES](https://github.com/JavaDominicano/conference/assets/2789130/86da7746-784c-41d8-8550-06e694758bf2)
@BrayanMnz está de acuerdo que sea así para la publicación?

**Comment by BrayanMnz** [comment]
Cambiar software engineer por JUG LEADER haría más sentido, no? 

Todo lo otro lo veo bien.

**Comment by ecabrerar** [comment]
![Brayan Muñoz - ES](https://github.com/JavaDominicano/conference/assets/2789130/19416de5-3a86-4ee4-a6de-723b536c0da9)
Listo

**Comment by BrayanMnz** [comment]
LGTM 👍🏾
