### ISSUE TITLE
JConf Dominicana Speaker Slides

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#339]
Crear una plantilla que servirá como base para las presentaciones de JConf Dominicana.

**Comment by fredpena** [comment]
Cual es la finalidad de esa plantilla, para tener un poco más de contextos.

**Comment by ecabrerar** [comment]
@fredpena tienes tiempo para trabajar este documento?

**Comment by fredpena** [comment]
Si, en los próximos días la estaré creando.

**Comment by ecabrerar** [comment]
@fredpena solo deben ir los logos de la comunidad Java de República Dominicana y la de JConf Dominicana.
aquí comparto el documento que te comenté que podías usar como guía:
https://docs.google.com/presentation/d/1B2X-y5qm0VJa6QO9WACID0dat52iXQGmjInEZqBIDg0/edit?usp=sharing
