### ISSUE TITLE
Investigar con eventos de PUCMM Santiago

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#345]
@vacax necesitamos investigar con eventos de Santiago los siguientes temas:

Espacios para almorzar
Donde ubicar los stands para los flash talks
Sillas y mesas

**Comment by BrayanMnz** [comment]
# Conferencia completada con éxito. 

## Espacio para almorzar 
- Centro de estudiantes 

## Donde ubicar los stands 
- Stands fueron colocados en el lobby del teatro 

## Sillas y mesas 
- Eventos PUCMM colocó sillas y mesas en el centro de estudiantes para el almuerzo.
