### ISSUE TITLE
Diseño de camiseta para JConf Dominicana 2024

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#346]
La t-shirt debe incluir el logo de jconf dominicana de forma destacable.
https://drive.google.com/file/d/1bVXPLSB5ED-CbO-SIBIzQ-1LdEhHlgAs/view?usp=drive_link

Además del logo, tenemos un slogan:
ES:
La Conferencia de Tecnologías Java del Caribe

EN:
The Caribbean Java Technologies Conference

El logo de la comunidad [Java Dominicano](https://drive.google.com/drive/folders/100TZCjmMgqR1FjzPwexQ2nfBgxnbm1GT?usp=sharing) debe aparecer.

También el logo de pucmm:
https://drive.google.com/drive/folders/100TZCjmMgqR1FjzPwexQ2nfBgxnbm1GT?usp=sharing

**Comment by ecabrerar** [comment]
@AnthonyBeato @fredpena nos gustaría tener un draft del diseño de la camiseta para la reunión del próximo martes 18 de Junio

**Comment by ecabrerar** [comment]
@AnthonyBeato ha podido ver algo de esto?

**Comment by AnthonyBeato** [comment]
> @AnthonyBeato ha podido ver algo de esto?

Saludos, así es. He estado muy atareado estos días y por ello aún no he mandado drafts, pero en esta fin de semana tengo pactado el crearlos para ya mostrarlos el martes 18.
