### ISSUE TITLE
Diseño de certificado de participación en los talleres

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#348]
Crear una plantilla para los certificados a entregar a los participantes de los talleres

**Comment by ecabrerar** [comment]
@NightmareVCO favor colaborar con esta tarea.
El próximo martes 2, la estaremos revisando.

**Comment by NightmareVCO** [comment]
@BrayanMnz @ecabrerar favor revisar cambios

**Comment by ecabrerar** [comment]
@BrayanMnz  favor enviar este draft a camacho para su aprobación https://drive.google.com/file/d/1LpG4jLNIRIkqodmc3DN6Eg8Uxw1ybUsM/view?usp=drive_link

**Comment by BrayanMnz** [comment]
Correo enviado, estamos a espera de confirmación de parte de Editorial y Camacho.

**Comment by BrayanMnz** [comment]
Certificados impresos y entregados a participantes.
