### ISSUE TITLE
Crear banner con todos los conferencistas

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#359]
Necesitamos un banner parecido a este:
https://drive.google.com/file/d/1iPjHTV7sjQKy7CiH3rn8XSPyeLIShYLw/view?usp=drive_link

Debemos usar la plantilla con la que hicimos este:
https://drive.google.com/file/d/1WcwEtztqYcJ7Aj1nGXfjRud6MEh1EPK5/view?usp=sharing

**Comment by ecabrerar** [comment]
@fredpena ya tu había creado una con todos los speakers, tomar esa que había creado y ponerle los logos de la tecnología como la plantilla que mencioné ahí

**Comment by fredpena** [comment]
Concluido
