### ISSUE TITLE
Crear banner de sold out

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#360]
Usando la misma plantilla, agregar el letrero de sold out
https://drive.google.com/file/d/1WcwEtztqYcJ7Aj1nGXfjRud6MEh1EPK5/view?usp=sharing

**Comment by NightmareVCO** [comment]
@ecabrerar Solicite acceso

**Comment by NightmareVCO** [comment]
@ecabrerar favor revisar versiones iniciales
