### ISSUE TITLE
Crear un banner en inglés

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#361]
Con este mismo diseño, vamos crear uno en inglés.
https://drive.google.com/file/d/1WcwEtztqYcJ7Aj1nGXfjRud6MEh1EPK5/view?usp=drive_link

**Comment by NightmareVCO** [comment]
@ecabrerar favor revisar versión inicial

**Comment by ecabrerar** [comment]
@NightmareVCO le hicimos algunas modificaciones
