### ISSUE TITLE
Panel Mujeres en Tecnología Java -  JConf Dominicana 2022

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/conference#85]
Panelistas:

Nombre :
Posición Laboral / Descripción:
Compañia:
Biografía Corta  :

Foto perfil: (preferible 400x400, ejemplo: la imagen del perfil de twitter)

Social Media:
Twitter / Github / linkedin / Blog / Web Site

**Comment by Sahira22** [comment]
**Nombre**: Mareubi Lynette García Espiritusanto
**Posición** Laboral / Descripción: Programadora
**Compañia**: Ministerio de Hacienda
**Biografía Corta**: Soy una joven creyente, agradable, dispuesta y pro-activa, con capacidades conductuales y técnicas, amante a la tecnología y orientada en obtener el logro de los objetivos de la empresa y proseguir con mi desarrollo profesional.

**Foto perfil: (preferible 400x400, ejemplo: la imagen del perfil de twitter)** :
https://media-exp1.licdn.com/dms/image/C4E03AQEIm8Ol575GCw/profile-displayphoto-shrink_800_800/0/1643306420333?e=1663200000&v=beta&t=22i4s5ApH-tXezYNyyqXcW3gK2NjtZeC1QWKzwSczEE

Social Media: Mareubi García - linkedIn
Linkedin: https://www.linkedin.com/in/mareubi-lynette-garc%C3%ADa-espiritusanto-54b3751a0

**Comment by ecabrerar** [comment]
Name : Mirna N. De Jesús Cambero

Last Position:
Title: Principal Software Engineer

Description: Led the development of Exchange Software by triaging customer requirements and delegating work to all technical resources on the team. Participated in the gathering of requirements, architecture design of new components, testing of functionality and performance, and maintenance of all components of Exchange Software.

Company: LTSE

Short Biography:

Mirna has a decade of Software Development experience working on large projects in the areas of healthcare, telecommunications, and FinTech. Her past experiences as a Principal Software Engineer at LTSE, SOS-Developer at Orange Dominicana, and Team Lead at Telvent Global Services, has given her deep expertise in the Java Language and Software Development practices. Mirna has been recognized as a young Software Developer in the Dominican Republic on a number of occasions. By excelling as a software engineer, she aims to have a positive impact on society and inspire other women. She holds a Software Development Technologist degree from ITLA and a B.Sc. in Information Systems from UNAPEC.

Social Media: 

https://www.linkedin.com/in/mirnadejesus/

![mirna](https://user-images.githubusercontent.com/2789130/178753701-95d13d53-56d3-48af-8973-e02eac9dd342.png)

**Comment by Sahira22** [comment]
**Nombre** : Janet Batlle Lasose
**Posición Laboral / Descripción:** Ingeniero IT
**Compañia:** Altice 
**Biografía Corta :** Graduated in Systems Engineering from UNPHU, with a postgraduate degree in Computer Technology from Intec, she has worked in the technology sector for around 20 years, 15 of which were in Jamaica as an IT Manager. Listening to music, watching movies, fishing and working in his garden are some of his favorite activities.

Graduada de Ingeniería en Sistemas de la UNPHU, con un posgrado de Computer Technology en Intec, ha trabajado en el sector tecnológico por alrededor de 20 años de los cuales 15 de ellos fueron en  Jamaica como IT Manager. Escuchar música, ver películas, pescar y trabajar en su huerto son de sus actividades preferidas.

**Foto perfil:** (preferible 400x400, ejemplo: la imagen del perfil de twitter)
https://media-exp1.licdn.com/dms/image/C4E03AQHjoICvFYtuxg/profile-displayphoto-shrink_800_800/0/1517369105377?e=1663200000&v=beta&t=G6FPlZp2Yaa3EfErflZmhsMQh4BMEcngUWUllzNKLGs

**Social Media:**
Linkedin: https://www.linkedin.com/in/janet-batlle-lasose
